version: '3.7'
services:
  app:
    # node is the image and 8-alpine is the tag
    image: node:8-alpine
    env_file: ./basic-nodejs-api/.env
    volumes:
      # only mounting specific folder and files to avoid including senstive data
      - ./basic-nodejs-api/src:/opt/app/basic-nodejs-api/src
      - ./basic-nodejs-api/test:/opt/app/basic-nodejs-api/test
      - ./basic-nodejs-api/package.json:/opt/app/basic-nodejs-api/package.json
      - ./basic-nodejs-api/package-lock.json:/opt/app/basic-nodejs-api/package-lock.json
      - ./app.sh:/opt/app/app.sh
    working_dir: /opt/app/basic-nodejs-api
    ports:
      # the first port number is the port number to be exposed
      # the second is the app's port number in the container
      - 3001:3001
      - 3002:3002
    command: ../app.sh
