version: '3.7'
services:
  app:
    image: node:8-alpine
    volumes:
      - ./basic-nodejs-api/src:/opt/app/src
      - ./Makefile:/opt/app/Makefile
    working_dir: /opt/app
    ports:
      - 3001:3001